### PR TITLE
Update sh1106.py

### PR DESCRIPTION
**Pull request by peter-l5**
This fork is intended to fix issue #25 by amending the y+h parameter of the methods vline, fill_rect and rect to y+h-1.

### CODE REVIEW

**Review by CRImier — APPROVED** [review]
looks good to me!

**Comment by robert-hh** [comment]
@CRImier: Did you test that change?

**Comment by CRImier** [comment]
no, merely read through code - it makes sense to me, and the change is obvious enough that there should be no side effects! I don't have my testing setup with me at the moment. Would you like this to be tested? I can see to it!

**Comment by robert-hh** [comment]
I prefer to have changes tested.

**Comment by peter-l5** [comment]
This pull request is intended to provide the enhancement discussed under issue #28.
The change to the code is as proposed in the discussion.
I have tested the code as part this [SH1107 driver](https://github.com/peter-l5/SH1107) which is based on this one, but not as part of this SH1106 driver directly since I do not have a SH1106 display. However as it affects the interface with the FrameBuffer class rather than the display, I believe that should form an adequate test.

**Comment by peter-l5** [comment]
reopened as closed in error

**Comment by robert-hh** [comment]
Why did you close the PR?

**Comment by peter-l5** [comment]
Closing the PR was a mistake. [I'm new to git and still learning how to use GitHub properly (which I'm doing through the web interface rather than a client).] Apologies for the trouble and hopefully nothing broken!

**Comment by robert-hh** [comment]
No. Reopened

**Comment by peter-l5** [comment]
Please see comments added to issue #25

**Comment by robert-hh** [comment]
Merged to master with a slight change of using `color` instead of `c` in the method `pixel.`

**Pull request closed without merging**
